name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: nginx
      ports:
        - 80
        - 443
      volumes:
        - test/fixtures:/var/www/server.localhost
        - test/vhosts:/etc/nginx/conf.d
        - test/certs:/etc/nginx/certs
        - h5bp:/etc/nginx/h5bp
        - nginx.conf:/etc/nginx/nginx.conf
        - mime.types:/etc/nginx/mime.types

    steps:
      - uses: actions/checkout@v1
      - uses: h5bp/server-configs-test@2.0.1
        with:
          tests: basic-file-access:caching:cache-busting:custom-errors:forbidden-files:precompressed-files-gzip:rewrites:ssl
      - uses: h5bp/server-configs-test@2.0.1
        with:
          tests: benchmark
